#!/usr/bin/env bash
# lib.sh — shared helpers for the benchmark harness. Sourced by the other
# scripts; never executed directly.
#
# Design rules (see docs/benchmark.md):
#   - All run captures live under $BENCH_OUT (default: /tmp/pi-bench),
#     OUTSIDE every repo — a file in a repo's tree is a dirty working tree.
#   - No framework: bash + git + jq. Every script is self-contained except
#     for the functions in this file.
#
# This file defines functions and read-only path variables. It does not
# mutate the caller's environment beyond the exported BENCH_* variables.

# --- Resolve paths relative to this file ------------------------------------
bench_lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BENCH_DIR="${BENCH_DIR:-$bench_lib_dir}"
TASKS_DIR="${TASKS_DIR:-$BENCH_DIR/tasks}"
BENCH_OUT="${BENCH_OUT:-/tmp/pi-bench}"

# --- Task helpers -------------------------------------------------------------

# task_dir <id> — prints the task directory; dies if absent.
task_dir() {
  local id="$1"
  local dir="$TASKS_DIR/$id"
  if [ ! -d "$dir" ]; then
    echo "task '$id' not found (expected $dir)" >&2
    return 1
  fi
  echo "$dir"
}

# task_env <id> — loads a task's task.env into the caller's environment.
# task.env is a KEY=VALUE file (values are trusted — operator-supplied).
# Returns 1 if the file cannot be sourced.
task_env() {
  local id="$1" dir
  dir="$(task_dir "$id")" || return 1
  if [ ! -f "$dir/task.env" ]; then
    echo "task '$id': missing task.env" >&2
    return 1
  fi
  # shellcheck source=/dev/null
  source "$dir/task.env"
}

# require_task_fields <id> — checks that all fields required by the harness
# are set in task.env; prints the first missing one and returns 1.
require_task_fields() {
  local id="$1" field
  task_env "$id" || return 1
  for field in REPO BASE_SHA TEST_CMD; do
    if [ -z "${!field:-}" ]; then
      echo "task '$id': missing required field $field in task.env" >&2
      return 1
    fi
  done
  # FIX_COMMIT or FIX_SHA must be set (either name is accepted).
  if [ -z "${FIX_SHA:-}" ] && [ -z "${FIX_COMMIT:-}" ]; then
    echo "task '$id': missing required field FIX_SHA (or FIX_COMMIT) in task.env" >&2
    return 1
  fi
  return 0
}

# --- Arm helpers ---------------------------------------------------------------

# arm_run_dir <task> <arm> <run#> — prints and creates the run's output dir.
arm_run_dir() {
  local task="$1" arm="$2" run="$3"
  local dir="$BENCH_OUT/$task/$arm/$run"
  mkdir -p "$dir"
  echo "$dir"
}

# run_repo_dir <task> <arm> <run#> — prints the fresh-clone path for a run.
run_repo_dir() {
  local task="$1" arm="$2" run="$3"
  echo "$BENCH_OUT/$task/$arm/$run/repo"
}

# --- pi shim setup ---------------------------------------------------------------

# install_pi_shim <run-dir> — writes a `pi` wrapper into <run-dir>/bin/pi
# that logs every invocation and then runs the real pi.
#
# run-arm.sh prepends <run-dir>/bin to PATH so that Claude's Bash tool finds
# the shim first (it resolves `pi` via PATH lookup in the child process).
#
# Behaviour:
#   --mode json (review-loop path):
#     - tee pi's stdout (one JSON object per line) to <run-dir>/pi-<N>.jsonl
#       where <N> is a per-process counter (date +%s%3N + $$).
#     - collect.sh parses usage from the per-call JSONL files.
#   text mode (oneshot path):
#     - record argv + wall clock + exit code to <run-dir>/pi-calls.jsonl.
#     - the per-call token count is not available (text mode has no usage
#       events); collect.sh reports pi_tokens as null for those calls.
#     - This is the documented token-accounting gap (docs/benchmark.md).
#
# --no-context-files: injected exactly once if not already present in argv.
# This enforces the operator's decision (issue #41: pi runs without project
# context files) for the pi-oneshot path without editing the shipped skill.
# pi-review-loop already passes it itself, so the injection is a no-op there.
install_pi_shim() {
  local run_dir="$1" bin_dir="$1/bin"
  mkdir -p "$bin_dir"
  local shim="$bin_dir/pi"

  # Resolve the real pi path at install time so the shim is stable even if
  # PATH changes between install and invocation.
  local real_pi
  real_pi="$(command -v pi)" || {
    echo "install_pi_shim: pi not found on PATH" >&2
    return 1
  }

  # shellcheck disable=SC2154  # shim variables are set inside the heredoc below
  cat > "$shim" <<SHEOF
#!/usr/bin/env bash
# pi shim — benchmark harness (docs/benchmark.md §pi-shim).
# Generated by bench/lib.sh install_pi_shim. Do not edit.
set -u

REAL_PI="$real_pi"
RUN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG_FILE="${PI_SHIM_LOG:-$RUN_DIR/pi-calls.jsonl}"
CALL_TAG="$(date +%s%3N)_$$"

args=("$@")

# Inject --no-context-files exactly once if not already present.
injected=0
for a in "${args[@]}"; do
  if [ "$a" = "--no-context-files" ] || [ "$a" = "-nc" ]; then
    injected=1
    break
  fi
done
if [ "$injected" -eq 0 ]; then
  args+=(--no-context-files)
fi

# Detect --mode json in argv (adjacent pair).
json_mode=0
prev=""
for a in "${args[@]}"; do
  if [ "$prev" = "--mode" ] && [ "$a" = "json" ]; then
    json_mode=1
  fi
  prev="$a"
done

t0="$(date +%s%3N)"
err_file="$RUN_DIR/pi-err-$CALL_TAG.tmp"
pi_out=""

if [ "$json_mode" -eq 1 ]; then
  # Review-loop path: capture stdout line-by-line to per-call JSONL.
  call_jsonl="$RUN_DIR/pi-$CALL_TAG.jsonl"
  "$REAL_PI" "${args[@]}" > "$RUN_DIR/pi-stdout-$CALL_TAG.tmp" 2> "$err_file"
  rc=$?
  # Append each line to the per-call JSONL and build the stdout string.
  while IFS= read -r line; do
    if [ -n "$line" ]; then
      echo "$line" >> "$call_jsonl"
      if [ -z "$pi_out" ]; then
        pi_out="$line"
      else
        pi_out="$pi_out\n$line"
      fi
    fi
  done < "$RUN_DIR/pi-stdout-$CALL_TAG.tmp"
  rm -f "$RUN_DIR/pi-stdout-$CALL_TAG.tmp"
else
  # Oneshot text-mode path: capture output, record argv + duration only.
  pi_out="$("$REAL_PI" "${args[@]}" 2> "$err_file")"
  rc=$?
fi

t1="$(date +%s%3N)"
dur_ms=$((t1 - t0))

# Build argv as a JSON array (jq -Rn '[inputs]' splits on newlines;
# args are single-line in practice — pi argv never contains newlines).
argv_json="$(printf '%s\n' "${args[*]}" | jq -Rn '[inputs]')"

# Append one metadata line to pi-calls.jsonl.
jq -cn \
  --argjson argv "$argv_json" \
  --argjson duration_ms "$dur_ms" \
  --argjson exit "$rc" \
  --arg mode "$([ "$json_mode" -eq 1 ] && echo json || echo text)" \
  --arg call_id "$CALL_TAG" \
  '{argv:$argv, duration_ms:$duration_ms, exit:$exit, mode:$mode, call_id:$call_id}' \
  >> "$LOG_FILE" 2>/dev/null

rm -f "$err_file"

# Always print pi's captured output (json mode: the event lines; text mode:
# the final text). Claude's Bash tool sees the same output it would have
# without the shim.
printf '%s' "$pi_out"

exit "$rc"
SHEOF
  chmod +x "$shim"
}

# --- Claude config-dir setup ---------------------------------------------------

# claude_config_dir <run-dir> — prints and creates a per-run CLAUDE_CONFIG_DIR.
#
# Subscription auth on macOS lives in the login keychain under
# "Claude Code-credentials", keyed by user account — NOT by config dir.
# A fresh CLAUDE_CONFIG_DIR therefore starts with no plugins/settings but
# still authenticates via the same subscription login (dry-run verified).
claude_config_dir() {
  local run_dir="$1"
  local dir="$run_dir/claude-config"
  mkdir -p "$dir"
  echo "$dir"
}

# install_pi_delegate_plugin <config-dir> <pinned-source-dir>
# Seeds the marketplace catalog in <config-dir> and installs the pi-delegate
# plugin from <pinned-source-dir> (a git clone of the pinned pi-delegate
# commit). The installLocation must be inside the config dir's tree, so the
# source is re-cloned under <config-dir>/plugins-src/pi-delegate first.
install_pi_delegate_plugin() {
  local config_dir="$1" src_dir="$2"
  local plugins_dir="$config_dir/plugins"
  local src_clone="$config_dir/plugins-src/pi-delegate"
  local parent
  parent="$(dirname "$src_clone")"
  mkdir -p "$parent"
  if [ -d "$src_clone" ]; then
    rm -rf "$src_clone"
  fi
  if ! git clone -q "$src_dir" "$src_clone"; then
    echo "install_pi_delegate_plugin: failed to clone $src_dir → $src_clone" >&2
    return 1
  fi
  mkdir -p "$plugins_dir"
  cat > "$plugins_dir/known_marketplaces.json" <<EOF
{
  "pi-delegate": {
    "source": { "source": "local", "path": "$src_clone" },
    "installLocation": "$src_clone",
    "lastUpdated": "$(date -u +%Y-%m-%dT%H:%M:%S.000Z)"
  }
}
EOF
  # Install into the config dir so it lands in the right plugin cache.
  CLAUDE_CONFIG_DIR="$config_dir" timeout 120 claude plugin install \
    pi-delegate@pi-delegate --json >/dev/null 2>&1 || true
}
